import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Deepdiview',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" data-theme="cupcake">
      <body>{children}</body>
    </html>
  );
}
